### ISSUE TITLE
How do we import and use plugins like we did in bootstrap-vue? Or do we even need to do this with "bootstrap-vue-next"

### ISSUE THREAD

**Issue by soorajsprakash** [bootstrap-vue/bootstrap-vue-next#1006]
**What you are trying to do.**

In `bootstrap-vue`, we could import plugins like shown below and use it directly. How can we do that with `bootstrap-vue-next`. 

```
consta app = createApp(App)

import {
    CardPlugin,
    ButtonPlugin,
    AlertPlugin
 } from "bootstrap-vue";

app.use(CardPlugin)
app.use(ButtonPlugin)
app.use(AlertPlugin)
```

**What you have already tried.** 

Tried the similar approach with `bootstrap-vue-next`.

**Any error messages you are getting.** 

* If we are doing like mentioned above, I'm getting `Module '"bootstrap-vue-next"' has no exported member 'xxxxPlugin'`
* But when i try using normal import like `import CardPlugin from "bootstrap-vue-next"`, then no error. And even I can use `app.use(CardPlugin)` without any errors. But is it the correct approach. 

I'm confused about the plugin support.

**Environment (please complete the following information):**

- OS: Ubuntu 22.10
- Package Version: 0.8.0
- Npm/Yarn/Pnpm Version: npm - 8.19.3

**Comment by VividLemon** [comment]
There are no plugins that achieve this functionality. To achieve this result, you should use the unplugin-vue-components BootstrapVueNext resolver. That way, you can use any component you want without the need for plugins, but while also automatically treeshaking everything. I'm not necessarily opposed to implementing the feature, but it seems redundant when there are better options. I myself did not know these things existed, nor would I ever use them in comparison to the other option of using the automatic resolver.

I am going to close this as 'not planned', but I am free to suggestions. Alternatively, you can implement the feature yourself and I will approve it. But I will not spend crucial time on this rarely used feature.
