### ISSUE TITLE
[0.8.0] b-form-radio doesn't work properly anymore with inline :options

### ISSUE THREAD

**Issue by mariusa** [bootstrap-vue/bootstrap-vue-next#1007]
**Describe the bug.** A clear and concise description of what the bug is.
```js
const countries = ref()

<b-form-radio-group
            v-model="countries"
            :options="['A', 'B', 'C']"
            class=""
        />

```
This used to work fine. With 0.8.0, clicking on any of the options doesn't select the radio anymore.

Changing to using a variable fixes it, but why is a variable necessary now?

```
const coptions = ['A', 'B', 'C']
<b-form-radio-group
            v-model="countries"
            :options="coptions"
            class=""
        />
```

**Comment by xvaara** [comment]
I believe we need to have the modelValue as passive here also.

**Comment by VividLemon** [comment]
> It's watchEffect again. @VividLemon we really shouldn't use watchEffect to update variables. It has weird sideEffects... sweat_smile

Please create a Vue Core issue about this issue we have been having

**Comment by VividLemon** [comment]
> It's watchEffect again. @VividLemon we really shouldn't use watchEffect to update variables. It has weird sideEffects... sweat_smile

This issue doesn't have anything to do with watch.

For some reason, when using :options="[1,2,3]" it calls the onUnmounted hook in the BFormRadio. I am guessing when you click the value, and it updates the modelValue, the subsequent options object is being rerendered, this causing onUnmounted to be called.

This is not an issue for when using a cached value, such as having it in an external ref or even computed, as the options array would not be rerendered, this no unUnmounted. 

Tricky situation for sure
