### ISSUE TITLE
<b-form-input class="w-md me-2"> generated markup duplicates classes

### ISSUE THREAD

**Issue by mariusa** [bootstrap-vue/bootstrap-vue-next#1010]
```
<b-form-input class="w-md me-2">
```
inspected in browser gives
```
<input id="__BVID__668496___BV_input__" class="form-control w-md me-2 w-md me-2"  ...
```

**Expected behavior.**
Don't duplicate classes

- Package Version: [e.g. 0.8.0]

Thanks

**Comment by VividLemon** [comment]
This is not necessarily a Bootstrap-vue-next issue. This is more of an issue with the merging of classes. I am going to close this issue as 'not planned'... However, I recommend create a Vue core issue, and linking this issue. I would also use this as a reproduction

**Comment by mariusa** [comment]
Thanks, that makes total sense!

**Comment by mariusa** [comment]
https://github.com/vuejs/core/issues/5055

**Comment by VividLemon** [comment]
> Thanks, that makes total sense!

> https://github.com/vuejs/core/issues/5055

Yeah, Vue's behavior is to optimistically merge the two class sets. Classes are the only situation were this occurs. But Evan is correct, it's not really an issue as it will cause no real noticeable difference to anyone that isn't staring at the elements classes

**Comment by VividLemon** [comment]
Though I am curious on what would happen if you did
```html
<template
  <Comp class="foo" />
```
&
```html
<template>
  <Comp :class="computedClass" @click="show = !show" />
</template>
<script setup>
import {computed,ref} from 'vue'
const show = ref(false)
const computedClass = computed(() => ({
  foo: show.value
}))
</script>
```
Would it still have foo? Or would it have 2 at one point, and 1 at another
