### ISSUE TITLE
b-form-checkbox @change is triggered before actual v-model is changed

### ISSUE THREAD

**Issue by mariusa** [bootstrap-vue/bootstrap-vue-next#1011]
**Is your feature request related to a problem? Please describe.**

Following up on https://github.com/bootstrap-vue/bootstrap-vue-next/issues/592

This still happens with `b-form-checkbox`:
```

let active = $ref(true)

function onActiveChange2() {
    console.log(`active 1 ${active}`)
    nextTick(async () => {
        console.log(`active 2 ${active}`)
    })
}

<b-form-checkbox
    v-model="active"
    switch
   @change="onActiveChange2()">
```

shows
```
active 1 true
active 2 false
```

Probably radios have the same issue.

**Comment by xvaara** [comment]
We should remove all the input and change emits and bind them to the native elements. It might be breaking change in related to bootstrapVue, but it's a better way to deal with them.
