### ISSUE TITLE
Documentation website is showing up blank

### ISSUE THREAD

**Issue by darrelfrancis** [bootstrap-vue/bootstrap-vue-next#1013]
Documentation page is blank

**To Reproduce.** Steps to reproduce the behavior:
1. Go to https://github.com/bootstrap-vue/bootstrap-vue-next 
2. Click on link "Documentation"
3. Redirects to https://bootstrap-vue.github.io/bootstrap-vue-next/

**Expected behavior.** A clear and concise description of what you expected to happen.
See documentation

**Screenshots.** If applicable, add screenshots to help explain your problem.
See white screen.
Console shows this:
~~~
Failed to load resource: the server responded with a status of 404 ()
app.3cd90746.js:1 TypeError: Cannot read properties of null (reading 'suspense')
    at setup (app.3cd90746.js:1:87399)
    at jt (app.3cd90746.js:1:18021)
    at bf (app.3cd90746.js:1:59630)
    at _f (app.3cd90746.js:1:59415)
    at H (app.3cd90746.js:1:46971)
    at X (app.3cd90746.js:1:46863)
    at b (app.3cd90746.js:1:43766)
    at Ss.A [as fn] (app.3cd90746.js:1:47946)
    at Ss.run (app.3cd90746.js:1:9381)
    at d.update (app.3cd90746.js:1:48217)
bd @ app.3cd90746.js:1
app.3cd90746.js:1 Hydration completed but contains mismatches.
u @ app.3cd90746.js:1
~~~

**Environment (please complete the following information):**

- OS: Windows

**Comment by GWillS163** [comment]
author already given resolutioin on other simliar issue, now we have to open docs file in repo for reading.

**Comment by darrelfrancis** [comment]
Ah thank you!

It turns out to be a problem in VuePress. The maintainer of this site is moving the docs to Nuxt, so for the meantime there is this link:

https://github.com/bootstrap-vue/bootstrap-vue-next/tree/main/apps/docs/docs/getting-started

Or you can clone the repo and read the docs locally.

**Comment by VividLemon** [comment]
Gj
