### ISSUE TITLE
[0.8.0] Booleanish not everywhere

### ISSUE THREAD

**Issue by susanne99** [bootstrap-vue/bootstrap-vue-next#1015]
b-form-invalid-feedback: prop "state" changed to Booleanish -> okay !
b-form-input: prop "state" still has the old style: "bool | null | undefined

not good, but in my case state will be feed by a "validatestate" method, which support a return type of booleanish or boolean|null, but not both !
in my app, typescript errors increase from 0 to 200 because of this problem

why did you change it, it was good enough in bootstrap vue:
_Contextual states
Bootstrap includes validation styles for valid and invalid states on most form controls.
Generally speaking, you'll want to use a particular state for specific types of feedback:
false (denotes invalid state) is great for when there's a blocking or required field. A user must fill in this field properly to submit the form.
true (denotes valid state) is ideal for situations when you have per-field validation throughout a form and want to encourage a user through the rest of the fields.
null Displays no validation state (neither valid nor invalid)_

**Comment by VividLemon** [comment]
This is why https://vuejs.org/guide/typescript/composition-api.html#syntax-limitations and it's known

**Comment by susanne99** [comment]
hmm, i don't understand you.

the problem is, that the prop "state" of  
b-form-invalid-feedback
b-form-input
have different type (in typescript)

bforminvalidfeedback.vue.d.ts(Line 79) ->  state: Booleanish | undefined;
bforminput.vue.d.ts(Line 234) ->  state: boolean | null | undefined;

that is not really okay. i cannot write one "validatestate-method" with one defined return type, either Booleanish or the other one. 

please, explain, why there are 2 different "state" types

exam snippet of my app:
`
 <b-input-group

 <b-form-input                                                           
       :state="validateState('tastbefund_fba_gleich')"
       :aria-describedby="uuid + 'fba_gleich_feedback'">
 </b-form-input>

 </b-input-group>

 <b-form-invalid-feedback  :id="uuid + 'fba_gleich_feedback'" 
        :state="validateState('tastbefund_fba_gleich')" >
        Invalid input
 </b-form-invalid-feedback>
`

**Comment by susanne99** [comment]
thank you !
