### ISSUE TITLE
[0.8.0] BFormRadioGroup input & change events are not working

### ISSUE THREAD

**Issue by ndavenia** [bootstrap-vue/bootstrap-vue-next#1022]
Since 0.8.0 the BFormRadioGroup @input event and @change event are never triggered 

**To Reproduce.** Steps to reproduce the behavior:

        <b-form-radio-group
          id="radio-group-1"
          v-model="radios.ex1.selected"
          :options="radios.ex1.options"
          name="radio-options"
          @change='onChange'
          @input='onInput'
          @update:modelValue='onModelValueChange'
        />

onInput & onChange are never called

**Expected behavior.**

onChange & onInput should be trigerred when user click on any radio of the group

**Environment (please complete the following information):**

**Additional context.** 
It was working with 0.7.x
using @update:modelValue can be a workaround, however the initial value may be triggered with "update:modelValue" but not with "change" or "input" events

**Comment by roelVerdonschot** [comment]
Also having and option with value 0 doesn't work. And switching between different options a few times stops v-model from updating. Tested in 0.8.0 and 0.8.1 
https://codesandbox.io/s/bootstrap-vue-next-b-form-radio-group-not-working-trxbxn?file=/src/App.vue

**Comment by afv** [comment]
The same happens with boolean values, broken between 0.7.3 and 0.8.0: https://codesandbox.io/s/bootstrap-vue-next-b-form-radio-group-not-working-forked-whsl62
