### ISSUE TITLE
[0.8.4] BCollapse not applying collapsed class to trigger element

### ISSUE THREAD

**Issue by Stoolbend** [bootstrap-vue/bootstrap-vue-next#1042]
**Describe the bug.** A clear and concise description of what the bug is.

The BCollapse component is not applying the `collapsed` class to the trigger element, like a button using the `v-b-toggle` directive. Therefore the trigger element content can't be set based upon collapsed status (as stated in the docs)

**To Reproduce.** Steps to reproduce the behavior:

The current example in the docs in the "Hiding and showing content in the toggle button based on collapse state" section reproduces this issue.
```
<div>
  <b-button v-b-toggle:my-collapse>
    <span class="when-open">Close</span><span class="when-closed">Open</span> My Collapse
  </b-button>
  <b-collapse id="my-collapse">
    <!-- Content here -->
    <div class="mt-2">This is data that's being collapsed</div>
  </b-collapse>
</div>
```
When clicking the button, you will see that the `collapsed` class is not applied to the button that triggers the component.

**Expected behavior.** A clear and concise description of what you expected to happen.

"When using the v-b-toggle directive, the class collapsed will automatically be placed on the trigger element when the collapse is closed, and removed when open."

**Environment (please complete the following information):**

- OS: Windows 11
- Package Version: 0.8.4
- Npm/Yarn/Pnpm Version: npm@9.3.1

**Additional context**

I have experienced this behaviour in 0.8.3 and 0.8.4. It was last working as specified in 0.7.3.

Many thanks

**Comment by xvaara** [comment]
The toggle isn't aware of the collapse state. and if collapse is triggered from somewhere else, we don't track that in the directive element. Not sure what's the right course of action here.

You can use the better way of using slots:
```html
       <b-collapse >
          <template #header="{visible, toggle, id}">
            <p>Visible: {{ visible }}</p>
            <b-button variant="primary" :aria-expanded="visible" :aria-controls="id" @click="toggle">
                <span v-if="visible">Close</span><span v-else>Open</span> My Collapse
            </b-button>
          </template>
          <div>content</div>
        </b-collapse>
```

**Comment by Stoolbend** [comment]
That example works perfectly for restoring the original functionality (prior to 0.8).
@xvaara Would you like me to do a PR to update the docs page for BCollapse to steer people to using the header slot instead?

**Comment by xvaara** [comment]
> That example works perfectly for restoring the original functionality (prior to 0.8).
> 
> @xvaara Would you like me to do a PR to update the docs page for BCollapse to steer people to using the header slot instead?

Any PR to docs is welcomed!

**Comment by IGx89** [comment]
Just ran into this myself. In my case I have one toggle controlling multiple collapses, so moving the toggle inside the collapse isn't possible. Looks like there's no desire to bring this functionality from bootstrap-vue into bootstrap-vue-next?
