### ISSUE TITLE
[0.8.4]  b-popover works different than in 0.7.3

### ISSUE THREAD

**Issue by susanne99** [bootstrap-vue/bootstrap-vue-next#1044]
a) prop "placement" - value "auto" is missing - It's a shame because it automatically calculated the position, and that can change depending on where the popover is installed

b) i use this: :delay="{ show: 1000, hide: 10 }"
    on my gui there are more elements with a popover functionality (fullcalendar events)
    now, it happens, that more than one popup is open, it does not close, when i move away with the mouse

all that worked in Version 0.7.3

**Comment by VividLemon** [comment]
@xvaara

**Comment by xvaara** [comment]
A: We could add the placement - auto using a middleware: https://floating-ui.com/docs/autoPlacement
Seems like a useful feature to have "in component".

B: Could you provide a "broken" example in a http://stackblitz.com/ or similiar? I'll investigate it soon.

**Comment by susanne99** [comment]
to a) if you want to use a 3" party library - its up to you - is just another library of which one is dependent.
maybe you can check how "bootstra vue" made.
https://bootstrap-vue.org/docs/components/popover

to b) take a look at the images below. this is a "bootstrap vue" app. 
there popover automatically determines the position - that is great, because it is (very) complicated to determine the position and therefore the arrow of the box 
the bar's are events on a day
![popup_below](https://user-images.githubusercontent.com/112922199/232105385-1e1248a1-38ff-45bc-acc8-d4257e1c9521.JPG)
![popup_above](https://user-images.githubusercontent.com/112922199/232105393-93fafa37-131f-4b3f-a48f-8974245c5445.JPG)

**Comment by VividLemon** [comment]
We expose 'floatingMiddleware' prop, so hypothetically, you could implement this yourself, as we find a solution. 

Though these pictures do not constitute a reproduction and don't help as much as a full reproduction would. Actual code comparisons of usage in BVN and BV would be more beneficial to see the differences.

**Comment by aki77** [comment]
In v0.8.0 and later, the popover element is always present.
This may cause scrolling and display corruption on some screens.

minimal reproduction:. https://stackblitz.com/edit/vue-ngnjrp

[![Image from Gyazo](https://i.gyazo.com/53bfb176a41d5cdb032a4f1a371f8218.gif)](https://gyazo.com/53bfb176a41d5cdb032a4f1a371f8218)

**Comment by susanne99** [comment]
> We expose 'floatingMiddleware' prop, so hypothetically, you could implement this yourself, as we find a solution.
> 
> Though these pictures do not constitute a reproduction and don't help as much as a full reproduction would. Actual code comparisons of usage in BVN and BV would be more beneficial to see the differences.

here a little snippet - it is very big spa app:
again, the same app works quite fine  with bootstrap vue next version 0.7.3 version, but not with 0.8.4
maybe you compare your code between the two versions
```
<b-popover
        custom-class="fullcalendartooltip"
        :target="targetid"
        placement="auto"
        :delay="{ show: 800, hide: 10 }"
        triggers="hover">

        <b-card
            no-body
            :style="{ 'background-color': backgroundcolor }">

            <template #header>
                <h5 class="mb-0">{{title}}</h5>
            </template>

            <b-card-body>
```

**Comment by susanne99** [comment]
> We expose 'floatingMiddleware' prop, so hypothetically, you could implement this yourself, as we find a solution.
> 
> Though these pictures do not constitute a reproduction and don't help as much as a full reproduction would. Actual code comparisons of usage in BVN and BV would be more beneficial to see the differences.

the solution has apparently already been given, namely in version 0.7.3 - i use this version in production - but the version 0.8.4. is too buggy in these points

**Comment by VividLemon** [comment]
> is too buggy in these points

I apologize using a free, pre-production library is giving you so many hardships.

**Comment by susanne99** [comment]
You don't need to apologize, it's clear that there are still errors in it. It is important that you take them all seriously and fix them step by step. I can sometimes help myself with workarounds, in an emergency I import the "old bootstrap vue" version

**Comment by xvaara** [comment]
> In v0.8.0 and later, the popover element is always present. This may cause scrolling and display corruption on some screens.
> 
> minimal reproduction:. https://stackblitz.com/edit/vue-ngnjrp

If you use container="body" they will be placed depending on their target position. You should remove the container prop and add position: relative to the scrollable div. https://stackblitz.com/edit/vue-amgpyv

**Comment by xvaara** [comment]
> the solution has apparently already been given, namely in version 0.7.3 - i use this version in production - but the version 0.8.4. is too buggy in these points

@susanne99  version before 0.8.0 use an old library for positioning the popover. You can continue to use 0.7.3 or you can help us find your problem. 

Looking at the code you provided tells me nothing helpful. The popover stays open if the mouse is hovering it or it has a focus (or the target is hover of course). We could add option to disable this if this is a problem for the users.

You can take look at https://github.com/bootstrap-vue/bootstrap-vue-next/blob/main/apps/playground/src/components/Comps/TPopover.vue for all the ways you can use the component.

**Comment by aki77** [comment]
> You should remove the container prop and add position: relative to the scrollable div.

@xvaara 
I got it.
Thanks!

**Comment by aki77** [comment]
@xvaara 

Is it intentional that the behavior of popover is significantly different from bootstrap?
I feel the standard behavior of bootstrap is easier to use.

When the component structure becomes complex, I feel that it is complicated to specify `position: relative` for the container element or to control it by specifying `container` from a child component.

**bootstrap standard behavior**

- Added to the body element
- The popover element exists in the DOM only during display.

https://getbootstrap.com/docs/5.1/components/popovers/

**Comment by xvaara** [comment]
@aki77 it should not significantly differ, but it does at some features (and has more features). We use a newer library than bootstrap, and that library requires that the element is in the dom, since it uses more modern browser features to calculate the position. 

as default it calculates the position related to the closest parent that has position relative (body has it if no other is defined). I found this easier to work with and you can overwrite some of the css variables for it in the parent.

I'll investigate if we can do something with the dom. Your original scroll problem comes from the fact that we place the popover even when it's not shown. Maybe we should but them all in 0,0 when not shown, so that overflow: scroll doesn't mess it up so much. 😄 Or we'd draw the element to dom hidden, and then wait for dom to update and calculate location and wait for dom again and then show the element...

**Comment by susanne99** [comment]
> > the solution has apparently already been given, namely in version 0.7.3 - i use this version in production - but the version 0.8.4. is too buggy in these points
> 
> @susanne99 version before 0.8.0 use an old library for positioning the popover. You can continue to use 0.7.3 or you can help us find your problem.
> 
> Looking at the code you provided tells me nothing helpful. The popover stays open if the mouse is hovering it or it has a focus (or the target is hover of course). We could add option to disable this if this is a problem for the users.
> 
> You can take look at https://github.com/bootstrap-vue/bootstrap-vue-next/blob/main/apps/playground/src/components/Comps/TPopover.vue for all the ways you can use the component.

i use the popover function as a tooltip for fullcalendar events. I have already used the code in vue2 with bootstrap vue, and the same code in vue3 with bootstrap vue next (0.7.3) and it worked perfectly. with 0.8.4. it doesn't work anymore if the new version is incompatible then you have to document it. you have to know what's different

**Comment by susanne99** [comment]
ok, new info
i remove the prop "placement" completly, then it determines automatically the position and caret of the popover - okay !
th eproblem with the multiple open popover still exists - here a snapshot from DOM
![DOM](https://user-images.githubusercontent.com/112922199/232666956-586a6379-a9b5-4e66-908e-466c1dca14df.JPG)
