### ISSUE TITLE
B-Table pagination mutates item prop (pull request available)

### ISSUE THREAD

**Issue by RuBaWa** [bootstrap-vue/bootstrap-vue-next#1047]
**Describe the bug.** A clear and concise description of what the bug is.
bootstrap-vue-next v0.8.4

Items in b-table are mutated by splice function at "computedItems" in b-table file

**To Reproduce.** Steps to reproduce the behavior:
1. Reactive table items
2. Pass items to b-table by :items props
3. Pass reactive current-page und per-page props
4. Change current-page prop
5. items array will be mutated by splice in "computedItems"

**Expected behavior.** A clear and concise description of what you expected to happen.
Items passed to b-table are immutable and are not mutated by pagination

**Solution:**
Replace B-Table at line 412

```
if (props.perPage !== undefined) {
    const startIndex = (props.currentPage - 1) * props.perPage
    return items.splice(startIndex, props.perPage)
}
```
with:
```
if (props.perPage !== undefined) {
    const startIndex = (props.currentPage - 1) * props.perPage
    const endIndex = startIndex + props.perPage > items.length ? items.length : startIndex + props.perPage
    return items.slice(startIndex, endIndex)
}
```

It will get items by index without mutating items array. Next time i will try a pull request.

**Comment by susanne99** [comment]
i have the same problem. pagination destroy the source of the "items" prop !!!! please, fix it asap, because pagination is a standard feature in our app's

**Comment by RuBaWa** [comment]
I have created a pull request for this issue. Maybe this issue can be closed?

[https://github.com/bootstrap-vue/bootstrap-vue-next/pull/1058](https://github.com/bootstrap-vue/bootstrap-vue-next/pull/1058)

**Comment by RuBaWa** [comment]
[https://github.com/bootstrap-vue/bootstrap-vue-next/commit/da0569c9c5824893e285472476b8f754fabbbdf6](https://github.com/bootstrap-vue/bootstrap-vue-next/commit/da0569c9c5824893e285472476b8f754fabbbdf6)
