### ISSUE TITLE
[0.8.4] data-attribute would be nice

### ISSUE THREAD

**Issue by susanne99** [bootstrap-vue/bootstrap-vue-next#1048]
in bootstrap vue, it was possible (on almost components) to set the data-attribute, for example:

`  <b-dropdown-item @click="onclick_searchtype"  data-searchtype="lastname">Lastname</b-dropdown-item>`

I use it a lot, and it's a handy way to assign data to an element.

**what do you thing, is it possible to add this feature as in bootstrap-vue ?**

**Comment by VividLemon** [comment]
Please gather documentation on Bootstrap-vue that highlights this behavior. I have never heard of this.

**Comment by susanne99** [comment]
it is not part of the official bootstrap vue documentation, but look here:
https://bootstrap-vue.org/docs/reference/changelog#bug-fixes-v2180
(search for "data-")
bootstrap vue didn't cut it away
the data-attribute is an important part for javascript programmer
https://developer.mozilla.org/en-US/docs/Learn/HTML/Howto/Use_data_attributes

standard components have a lot of data-attributes:
`<button type="button" class="btn btn-primary" data-bs-toggle="modal" data-bs-target="#exampleModal">`


**Q: How can i set my own  data-attributes now ?**

**Comment by susanne99** [comment]
this exam snippets works with data-attribut
```
 <b-form-select
          data-myjob="expert"
          :options="searchoptions"
          size="sm"
          v-model="searchtype" >
 </b-form-select>
```
**this does not work**
`<b-dropdown-item data-searchtype="lastname">Lastname</b-dropdown-item>`
