### ISSUE TITLE
[0.8.4] Directive: vbPopover and vbTooltip not working

### ISSUE THREAD

**Issue by susanne99** [bootstrap-vue/bootstrap-vue-next#1052]
both do not work at all.
it seems to be not implemented yet

**Comment by xvaara** [comment]
which part of this isn't working for you? 
https://stackblitz.com/edit/vue-dmggov?file=src%2FApp.vue
Maybe you've installed bootstrap-vue-next or the directives wrong?

**Comment by susanne99** [comment]
Wrong Directive, i used  vBPopover and vbTooltip
correct is v-b-popover and v-b-tooltip
thank you

A functioning and complete documentation would be helpful, then you would have to answer fewer problems

**Comment by soorajsprakash** [comment]
Hi, how are you using popover?
I just import bootstrapvuenext in main file and use it in app, with app.use()

Then w/o importing it again as a seperate component, i just did:
```
<v-b-popover id="tab-popover" target="on-create" trigger="hover" placement="bottom">
    <template #title>on Create</template>
    <div v-html="data.help.onCreate"></div>
</v-b-popover>
```

And its not working.
