### ISSUE TITLE
Is 'isExactActive' no longer used when using <BLink> component with RouterLink?

### ISSUE THREAD

**Issue by MyungGyu** [bootstrap-vue/bootstrap-vue-next#1060]
- OS: Windows 11
- Package Version: 0.8.6
- Npm/Yarn/Pnpm Version: npm@8.19.2

In version 0.7.3, there was a setting for 'isExactActive' in <BLink>. Is it no longer in use since version 0.8 or later?

**Comment by VividLemon** [comment]
Those props don't exist for vue-router@4
https://router.vuejs.org/guide/migration/#removal-of-the-exact-prop-in-router-link

**Comment by MyungGyu** [comment]
Thank you!
