### ISSUE TITLE
[0.8.6] B-TABLE: Attr "data-label" on <TD> still missing 

### ISSUE THREAD

**Issue by susanne99** [bootstrap-vue/bootstrap-vue-next#1064]
the "data label" attribute is missing from the td tag in the b-table cells. it would be great if that were available again, because then you can see the column names again in the stacked mode of the table. is important for mobile phones and tablets. Adding attributes with tdAttr does not work because data-label is not a member of the tdAttr interface. I use only typescript !!
Furthermore, the attributes are missing from the td-tag: "aria-colindex" and role="cell"

**Comment by VividLemon** [comment]
Stop opening duplicate issues
