### ISSUE TITLE
this.$bvModal → always undefined

### ISSUE THREAD

**Issue by rubebop** [bootstrap-vue/bootstrap-vue-next#1068]
I'm migrating an app to Vue 3. I decided to use bootstrap-vue-next instead of bootstrap-vue, since the latter only supports the migration build.

I have several modal windows, that I show or hide dynamically.

No matter what I do `this.$bvModal` remains `undefined`, hence an error is thrown when attempting to call the show or hide methods (previously everything was working fine).

What am I missing?

**Comment by VividLemon** [comment]
That specific behavior has been removed. Vue 3 doesn't really use global this methods. You will not find them often I believe. 

You're best off v-modeling to the modal, and making the variable globally available. Perhaps it may be revisit-able in the future to provide a similar functionality, specifically though a `composable`, but I'd have to confer with another developer

**Comment by susanne99** [comment]
here an example:
https://stackblitz.com/edit/vue-kvgkeh?file=src/components/confirmationdialog.vue

**Comment by rubebop** [comment]
I thank you both for your answers, which provide a solution to the problem.

I think that the downside, apart from the breaking change, is the fact that this way we have to declare an additional variable.

See the example from [Using this.$bvModal.show() and this.$bvModal.hide() instance methods](https://bootstrap-vue.org/docs/components/modal#using-thisbvmodalshow-and-thisbvmodalhide-instance-methods):
```
<div>
  <b-button id="show-btn" @click="$bvModal.show('bv-modal-example')">Open Modal</b-button>

  <b-modal id="bv-modal-example" hide-footer>
    <template #modal-title>
      Using <code>$bvModal</code> Methods
    </template>
    <div class="d-block text-center">
      <h3>Hello From This Modal!</h3>
    </div>
    <b-button class="mt-3" block @click="$bvModal.hide('bv-modal-example')">Close Me</b-button>
  </b-modal>
</div>
```

So, I guess I'll go for the `v-model` directive or the `model-value` attribute.

**Comment by rubebop** [comment]
Another important aspect related to this topic, is that the calling the `show` and `hide` functions via `$refs` also doesn't work:

```
<template>
    <b-modal
      ref="my-modal-window"
    >
      yoo
    </b-modal>
  </div>
</template>

<script>
export default {
[...]
 mounted() {
    this.$refs["modal-window"].show()
}
[...]
</script>
```

**Comment by rubebop** [comment]
Concerning the `show` method: I've tried releases _0.8.10_ and _0.9.4_ → now I don't get an error message, but nothing happens, so no modal window is being displayed.
Does it mean that the methods `show` and `hide` are not supported anymore and that the only way to do this is via v-modeling?

**Comment by suzumejakku** [comment]
As for me, the biggest drawback is the lack of Promise-based modals. I have a lot of those small "Confirm" modals for which I used $bvModal.msgBoxConfirm and wait on the promise result. There are some Vue 3 promise-based modals libraries out there, but of course none of them using bootstrap-vue-next...

**Comment by suzumejakku** [comment]
Just as a follow-up...
Based on [this article](https://stackabuse.com/how-to-create-a-confirmation-dialogue-in-vue-js/), I created my own simple component which is replacing all my previous $bvModal.msgBoxConfirm, etc. 

Here is the code of this component (sorry, no TS) :

```
<template>
  <b-modal v-if="setup"
           v-model="showModal"
           :centered="setup.centered"
           no-close-on-backdrop
           no-close-on-esc
           :hide-header-close="setup.hideHeaderClose"
           @close="handleHide('cancel')"
           cancel-disabled
           :ok-only="true">

    <template v-slot:title>
      {{ setup.title }}
    </template>

    <template v-slot:default>
      {{ setup.htmlMessage }}
    </template>

    <template v-slot:footer :class="setup.footerClass">
      <b-button :size="setup.buttonSize" @click="handleHide('confirm')" :variant="setup.okVariant" >{{ setup.okTitle }}</b-button>
      <b-button v-if="displayCancel" :size="setup.buttonSize" @click="handleHide('cancel')">{{ setup.cancelTitle }}</b-button>
    </template>

  </b-modal>
</template>

<script>
//inspired by https://stackabuse.com/how-to-create-a-confirmation-dialogue-in-vue-js/

import {defineComponent} from "vue";

export default defineComponent({
  name: "async-simple-confirm-modal",

  props: {
    setup: {
      type: Object,
      /*
        title: String,
        size: String,
        buttonSize: String,
        okVariant: String,
        okTitle: String,
        cancelTitle: String,
        footerClass: String,
        hideHeaderClose: Boolean,
        centered: Boolean
      })
       */
    },
    displayCancel: {
      type: Boolean,
      required: false,
      default: true
    },

  },
  data() {
    return {
      showModal: false,

      resolvePromise: undefined,
      rejectPromise: undefined,
    }
  },
  methods: {
    //this function must be called by the parent component using this.$refs.xxxx.show()
    show() {
      this.showModal = true
      return new Promise((resolve, reject) => {
        this.resolvePromise = resolve
        this.rejectPromise = reject
      })
    },

    handleHide(action) {
      this.showModal = false

      if (action === 'confirm') {
        this.resolvePromise(true)
      }
      else {
        this.resolvePromise(false)
        //could return: this.rejectPromise(new Error('The user rejected xxx'))
      }
    },
  }
})
</script>

<style>
</style>
```

The parent component would call it as follows: 

```
<template>
     <async-simple-confirm-modal ref="asyncConfirm" :setup="someSetup"/>
</template>

<script>
...

const confirm = await this.$refs.asyncConf.show()
      if (confirm) {
        //do something
      } else {
        //do something else
      }
...
</script>

```

There might be a better way, but this works for now :)

**Comment by VividLemon** [comment]
https://bootstrap-vue-next.github.io/bootstrap-vue-next/docs/components/modal.html#programmatically-control
