### ISSUE TITLE
can support b-sidebar

### ISSUE THREAD

**Issue by rayyrchen** [bootstrap-vue/bootstrap-vue-next#1080]
can support b-sidebar, like this https://bootstrap-vue.org/docs/components/sidebar

**Comment by VividLemon** [comment]
https://bootstrap-vue.github.io/bootstrap-vue-next/reference/components/offcanvas.html

**Comment by VividLemon** [comment]
& https://getbootstrap.com/docs/5.3/components/offcanvas/

**Comment by rayyrchen** [comment]
Oops, thank you for your help!

**Comment by phlegx** [comment]
> https://bootstrap-vue.github.io/bootstrap-vue-next/reference/components/offcanvas.html

This link is broken. Here the right link: https://bootstrap-vue-next.github.io/bootstrap-vue-next/reference/components/offcanvas.html
