### ISSUE TITLE
Is there a way to extend the variant colors?

### ISSUE THREAD

**Issue by nelson6e65** [bootstrap-vue/bootstrap-vue-next#1093]
**Is your feature request related to a problem?**

I have some custom theme colors in my Bootstrap build. When I try to use a custom variant color in `variant` prop, I get a typescript incompatibility error:

![imagen](https://github.com/bootstrap-vue/bootstrap-vue-next/assets/9272498/a4291fe7-0984-4111-8b8a-7026da5e672f)

**Describe the solution you would like.** 

I'd like to keep using typed variant, but using any of my custom Bootstrap color variant. Maybe a way to replace/extend the type, adding manually the compatible values.

**Describe alternatives you have considered.**

I'm forcing the type as a workaround:
```ts
const NAVBAR_VARIANT: ColorVariant = 'accent' as ColorVariant;
```

**Additional context.** 

Currently, `ColorVariant` is being based in hard-coded keys.
https://github.com/bootstrap-vue/bootstrap-vue-next/blob/e7af75a0012acc332ed970fef2b5a4d03da78755/packages/bootstrap-vue-next/src/types/ColorVariant.ts#L1-L12

**Comment by VividLemon** [comment]
https://bootstrap-vue.github.io/bootstrap-vue-next/reference/types.html
Near the bottom. There aren't any anchor links atm

**Comment by nelson6e65** [comment]
Thanks, @VividLemon.

I had to change the module path to make it to work:

```diff
import 'bootstrap-vue-next'

-declare module 'bootstrap-vue-next/dist/types' {
+declare module 'bootstrap-vue-next/dist/src/types' {
```

**Comment by VividLemon** [comment]
You should submit a PR. I didn't realize that this was broken. Something change in an update to one of the dependencies that changed the paths
