### ISSUE TITLE
Does the Carousel component work?

### ISSUE THREAD

**Issue by KenEucker** [bootstrap-vue/bootstrap-vue-next#244]
I am trying to use the BCarousel component but I can't get it to work and it doesn't appear to have an example in the docs: https://github.com/cdmoro/bootstrap-vue-3/tree/main/docs/components

There are no errors being displayed, all of the HTML appears to be there, but nothing is visible from the slides. This is all that you see:

<img width="340" alt="Screen Shot 2021-12-02 at 1 52 15 PM" src="https://user-images.githubusercontent.com/1720267/144509036-7700ae20-9ea8-4443-8f35-307f7d1aec0d.png">

Using this code from the Bootstrap-Vue documentation:
https://bootstrap-vue.org/docs/components/carousel

```vue
<template>
  <div>
    <b-carousel
      id="carousel-1"
      v-model="slide"
      :interval="4000"
      controls
      indicators
      background="#ababab"
      img-width="1024"
      img-height="480"
      style="text-shadow: 1px 1px 2px #333;"
      @sliding-start="onSlideStart"
      @sliding-end="onSlideEnd"
    >
      <!-- Text slides with image -->
      <b-carousel-slide
        caption="First slide"
        text="Nulla vitae elit libero, a pharetra augue mollis interdum."
        img-src="https://picsum.photos/1024/480/?image=52"
      ></b-carousel-slide>

      <!-- Slides with custom text -->
      <b-carousel-slide img-src="https://picsum.photos/1024/480/?image=54">
        <h1>Hello world!</h1>
      </b-carousel-slide>

      <!-- Slides with image only -->
      <b-carousel-slide img-src="https://picsum.photos/1024/480/?image=58"></b-carousel-slide>

      <!-- Slides with img slot -->
      <!-- Note the classes .d-block and .img-fluid to prevent browser default image alignment -->
      <b-carousel-slide>
        <template #img>
          <img
            class="d-block img-fluid w-100"
            width="1024"
            height="480"
            src="https://picsum.photos/1024/480/?image=55"
            alt="image slot"
          >
        </template>
      </b-carousel-slide>

      <!-- Slide with blank fluid image to maintain slide aspect ratio -->
      <b-carousel-slide caption="Blank Image" img-blank img-alt="Blank image">
        <p>
          Lorem ipsum dolor sit amet, consectetur adipiscing elit. Suspendisse eros felis, tincidunt
          a tincidunt eget, convallis vel est. Ut pellentesque ut lacus vel interdum.
        </p>
      </b-carousel-slide>
    </b-carousel>

    <p class="mt-4">
      Slide #: {{ slide }}<br>
      Sliding: {{ sliding }}
    </p>
  </div>
</template>

<script>
  export default {
    data() {
      return {
        slide: 0,
        sliding: null
      }
    },
    methods: {
      onSlideStart(slide) {
        this.sliding = true
      },
      onSlideEnd(slide) {
        this.sliding = false
      }
    }
  }
</script>
```

**Comment by edwh** [comment]
As mentioned elsewhere, you seem to need to have `active` set on a slide for it to show.

But I'm seeing other issues with this:
* The carousel indicators don't render.
* The next/previous buttons don't work - this seems to be related, as there's an error trying to remove the active class from the current indicator.

**Comment by snmuhein** [comment]
It seems that the Carousel still does not work as expected. I tried the following:

```vue
<script setup lang="ts">
import { ref } from 'vue';

const slide = ref<number | undefined>(0);
const images = [
  'https://picsum.photos/1024/480/?image=58',
  'https://picsum.photos/1024/480/?image=59',
  'https://picsum.photos/1024/480/?image=60',
];
</script>

<template>
  <div>
    <b-carousel
      id="carousel-1"
      :v-model="images"
      :model-value="slide"
      :interval="4000"
      controls
      indicators
    >
      <b-carousel-slide
        v-for="(image, index) in images"
        :key="`sliderImage-${index}`"
        :class="index === 0 ? 'active' : ''"
        :img-src="image"
      ></b-carousel-slide>
    </b-carousel>
    <p>Slide: {{ slide }}</p>
    <p>Images: {{ images }}</p>
  </div>
</template>

<style scoped></style>

```

Please add a working example to the [documentation](https://cdmoro.github.io/bootstrap-vue-3/components/Carousel.html)

**Comment by VividLemon** [comment]
https://github.com/cdmoro/bootstrap-vue-3/pull/691

**Comment by VividLemon** [comment]
> It seems that the Carousel still does not work as expected. I tried the following:

https://github.com/cdmoro/bootstrap-vue-3/pull/691

**Comment by dagnelies** [comment]
Now it should:

https://cdmoro.github.io/bootstrap-vue-3/components/Carousel.html

But I should update the doc, somehow it is suboptimal that the first demo looks like a plain image because controls and indicators are not enabled while the second one is barely visible because of dark mode and dark pictures. Oh well, at least it's there.

**Comment by snmuhein** [comment]
Yes, the basic examples from the documentation work.

But it does not work if the slides are created with v-for:

```vue
<script setup lang="ts">

const images = [
  'https://picsum.photos/1024/480/?image=31',
  'https://picsum.photos/1024/480/?image=32',
  'https://picsum.photos/1024/480/?image=33',
];
</script>

<template>
  <div>
    <b-carousel controls indicators>
      <!-- first slide -->
      <b-carousel-slide
        active
        img-src="https://picsum.photos/1024/480/?image=30"
      />

      <!-- more slides -->
      <b-carousel-slide
        v-for="(image, index) in images"
        :key="index"
        :img-src="image"
      ></b-carousel-slide>
    </b-carousel>
  </div>
</template>

```

**Comment by dagnelies** [comment]
That's a pity. When I sent the MR to fix, I had a look at the component and could figure out how it works. 

https://github.com/cdmoro/bootstrap-vue-3/blob/main/packages/bootstrap-vue-3/src/components/BCarousel/BCarousel.vue

It basically renders the HTML normally and invokes the bootstrap Carousel code on top when mounted. I guess the `v-for` introduces some dynamics which makes it incompatible. I guess for proper carousel support with all the fluff, including dynamic slides, just wrapping it isn't enough and the native [bootstrap carousel code](https://github.com/twbs/bootstrap/blob/main/js/src/carousel.js) should be ported too. I guess it cannot be done with a "small fix" and someone else must get its hand dirty. ;)

**Comment by VividLemon** [comment]
It would be nice to try to transition away from using Bootstrap js code and using only Vue internally. The carousel js code is relatively simple, which is nice. Most of it is handling some event listeners, and controlling how the images change. Both of which are extremely simple, thanks to Vue. But it's not very important to get to.

**Comment by gvaliani** [comment]
I have found that this works if indicators are not set in b-carousel. Just ```<b-carousel controls>```.

**Comment by dagnelies** [comment]
@gvaliani  Actually, the indicators should work ...as long as the active slide is the first one.

If another slide is the starting one, there is an undocumented property to add: `<b-carousel indicators starting-slide="2" ...` where the first slide starts with index 0. It's a bit ugly but I didn't know how to make it right.

Not to next developer/fixer: the whole `active` thing should IMHO actually be an integer property of the carousel (`<b-carousel active="2" ...>` rather than a boolean property of the slide.

**Comment by VividLemon** [comment]
Should have been completed for a few months. Make a new ticket if any issues are found https://bootstrap-vue.github.io/bootstrap-vue-next/components/Carousel.html
