### ISSUE TITLE
Manually show/hide a popover

### ISSUE THREAD

**Issue by pierrewtLanca** [bootstrap-vue/bootstrap-vue-next#257]
Hi, 

I may have missed something and used popover wrongly.

As available in the current version of the library (thanks for the great work !) I'm using the "v-b-popover" on an input element to show a popover.
When I use for example` v-b-popover.hover.left="blabla"`, the popup shows fine.

However, I want to be able to manually trigger/hide the popover to suit my UI workflow. So, I've changed the directive to this `v-b-popover.manual.left="blabla"`, and in my code, call for example this: `this.$root.$emit("bv::show::popover", this.titleInputId)` (where this.titleInputId returns the id of the input element the popup should trigger on). I followed this link for reference : [Boostrap-vue](https://bootstrap-vue.org/docs/directives/popover).

Nothing happens then. Have I made a mistake somewhere or is this not yet available in the library?

Thanks,
Pierre

**Comment by xvaara** [comment]
The link you used for reference is for vue 2 version.
In Vue 3 the emits are different. We don't support $root or $emit on it anymore. You should use a component and a v-modal to manually trigger them.  I think you can use an object on the directive: v-b-popover="{modelValue: youVariable, title: 'title, content: 'content'}", but haven't tested that.

You can check: https://github.com/bootstrap-vue/bootstrap-vue-next/blob/main/apps/playground/src/components/Comps/TPopover.vue for the many ways of using the BPopover component.

@VividLemon close.

**Comment by PwtKCL** [comment]
Hi,
Thanks for your answer.  The project I work with is using Vue 2. And we are not going to upgrade the library soon.
To be honest I forgot now how I addressed the issue... so I guess I found a way to do things regardless.
Best regards,
Pierre
