### ISSUE TITLE
Popover events don't work

### ISSUE THREAD

**Issue by aleksvaganoff** [bootstrap-vue/bootstrap-vue-next#282]
When adding the handler to a `<b-popover>` element it isn't triggered. For example:
```
<b-popover @show="onShow" target="popover-button-sync" triggers="click" title="Popover">
  Hello <strong>World!</strong>
</b-popover>
```
where "onShow" never is executed, even if popover is visible.

It seems it happens because the target element is defined after "mount" event of the component. But all bootstrap handlers are defined on "mount" event. See screen
![image](https://user-images.githubusercontent.com/16879394/154705005-69b86412-cd97-41d5-879c-64705479651d.png)

**Comment by NNeto** [comment]
This is still an issue, right? I tried using the events from `b-popover` but to no success. Currently on 0.3.12

**Comment by VividLemon** [comment]
There has been no progress on that component. I think another contributor was toying with the idea of moving that component off of using popper to handle the functionality and using a vue specific solution. 

As it stands, unlike the few other components that need to be moved off of bootstrap js, this one likely needs more attention

@xvaara do you have an update on possibly using that other package? I believe you were the one that mentioned replacing popperjs?
