### ISSUE TITLE
<b-form-select class='w-md'> generates class="form-select w-md w-md"

### ISSUE THREAD

**Issue by mariusa** [bootstrap-vue/bootstrap-vue-next#311]
Custom class is repeated twice
`class="form-select w-md w-md"`

https://github.com/cdmoro/bootstrap-vue-3/blob/4ee50a9a7256621bea3e029ad65a57ec3f962ddf/src/components/BFormSelect/BFormSelect.vue#L104

**Comment by xvaara** [comment]
yeah, there should be inheritAttrs: false, if there is v-bind="$attrs". or no v-bind, since they pretty much do the same thing.

**Comment by VividLemon** [comment]
https://github.com/bootstrap-vue/bootstrap-vue-next/issues/1010

Duplicate. Lets keep any convos over there
