### ISSUE TITLE
Automatic import error for some components

### ISSUE THREAD

**Issue by tghkuma** [bootstrap-vue/bootstrap-vue-next#388]
With the [feat: support for library authors for nuxt3](https://github.com/cdmoro/bootstrap-vue-3/pull/367)  function, `Uncaught SyntaxError: import not found: default` error occurs if import is not used in the following components.

- BContainer
- BDropdown
- BCollapse
- BPopover

If you use import, the following error will occur in JS console.
```
<script lang="ts" setup>
import { BContainer } from 'bootstrap-vue-3'
  :
</script>
```

```
[Vue warn]: Component "Xxxx" has already been registered in target app.
```
![スクリーンショット_2022-05-08_001032](https://user-images.githubusercontent.com/1668567/168162351-f427fa02-ede8-4957-b0c9-3c0079cb2334.png)

**Comment by messenjer** [comment]
Hello,

If you configure Nuxt3 like that https://cdmoro.github.io/bootstrap-vue-3/getting-started/#installation-nuxt-js-3 

You don't need to import your component.

More info here: 

https://v3.nuxtjs.org/guide/concepts/auto-imports
https://v3.nuxtjs.org/guide/directory-structure/components#library-authors

Regards

Mathieu

**Comment by tghkuma** [comment]
@messenjer 

`Uncaught SyntaxError: import not found: default` error occurs if import is not used in the following components.
Other components didn't need import.

- BContainer
- BDropdown
- BCollapse
- BPopover

![スクリーンショット_2022-05-08_001105](https://user-images.githubusercontent.com/1668567/168421699-987d11b2-a86a-4c9e-bca8-e5c0aa499874.png)
