### ISSUE TITLE
Does not work when b-collapse changes pages

### ISSUE THREAD

**Issue by tghkuma** [bootstrap-vue/bootstrap-vue-next#390]
Does not work when b-collapse changes pages.

It works only for the first time on the 1st page, but not on the 2nd page.
After that, even if you return to the 1st page, it will not work.

https://stackblitz.com/edit/nuxt-starter-4azvqh

#278 Same Problem.
I tried adding `<ClientOnly>` but it didn't fix the problem

**Comment by xvaara** [comment]
@VividLemon I think this is fixed also.
