### ISSUE TITLE
Tooltip Doesn't work in nuxt

### ISSUE THREAD

**Issue by imanmalekian31** [bootstrap-vue/bootstrap-vue-next#660]
**Describe the bug**
When I use tooltip directive in Nuxt project ( In pure Vue app it's ok), I get this Error (`ssr:false`): 

![Screenshot from 2022-09-13 17-19-17](https://user-images.githubusercontent.com/58827166/189905779-20b6a886-3549-4785-8e18-8fa99621d5ed.png)

**Comment by VividLemon** [comment]
I still imagine that it has to do with Bootstrap, and I believe it's related to their methods to find elements in the DOM. It's odd that SSR false won't work, but until a future version of Bootstrap, there is nothing we can do

**Comment by imanmalekian31** [comment]
Did you test that?

**Comment by VividLemon** [comment]
Did I test that it's a Bootstrap issue, or that it's our issue?

**Comment by VividLemon** [comment]
On second look, my answer is incorrect. This problem is the result of an improper nuxt config file on our end. Since Nuxt isn't fully supported, I'm not going to make it a priority, as compared to other issues that exist. But I will look into it and ask around the Nuxt discord and things, since the documentation for writing a Nuxt module is difficult to understand.

**Comment by imanmalekian31** [comment]
Thank you for responding.

**Comment by tghkuma** [comment]
@VividLemon [Installation - Nuxt.js 3](https://cdmoro.github.io/bootstrap-vue-3/getting-started/#installation-nuxt-js-3)  only installs components, no directives.
Calling `app.use(BootstrapVue3)` raises #388.
Because `module` refers to `src` and `app.use()` refers to `dist`.

**Comment by VividLemon** [comment]
> Hello. i've got this problem without nuxt. It comes from the directives import name, first uppercase letter is no longer accepted with <script setup> To solve this problem, you have to rename directive following <script setup> rule.

#685

**Comment by likymm** [comment]
Any update on this? Seems like the tooltip doesn't work on the documentation. Thanks

**Comment by VividLemon** [comment]
> Any update on this? Seems like the tooltip doesn't work on the documentation. Thanks

No change yet. Sorry

**Comment by bettysteger** [comment]
I got the same error: `Failed to resolve directive: b-tooltip` when using the Legacy installation (when using webpack)!

**Comment by VividLemon** [comment]
One could attempt to add 
```ts
// nuxt.config.ts
bootstrapVueNext: {
  plugins: {all: false},
  composables: {all: false},
}
```
To nuxt.config.ts

**Comment by sky-code** [comment]
I got the same error: `Failed to resolve directive: b-tooltip` with 
`bootstrap-vue-next: 0.7.3` and `nuxt: 3.2.0`

**Comment by VividLemon** [comment]
> This is marked as completed, however, I have not been able to make it work. Also getting `Failed to resolve directive: b-tooltip`. Is there any example? I'm using
> 
> ```
> "nuxt": "3.4.3",
> "@bootstrap-vue-next/nuxt": "0.0.6",
> "bootstrap-vue-next": "0.8.10",
> ```
> 
> ```
> bootstrapVueNext: {
>     composables: true,
>     directives: {vBTooltip: true, all: false}
> },
> ```

Import directives directly. There was some issue with having them auto import. I'd have to look at it more on why it wasn't working
