### ISSUE TITLE
feat(navbar): fully collapse navbar when action clicked

### ISSUE THREAD

**Issue by memen45** [bootstrap-vue/bootstrap-vue-next#721]
**Describe the bug**
Not sure if this is a bug report or feature request. Navbar collapse does not collapse when clicking a b-navbar-item with e.g. `to="/"` or `href="#"`. In [Bootstrap](https://getbootstrap.com/docs/5.2/components/navbar/#supported-content) this seems to be default behaviour, however in Bootstrap Vue the navbar would actually collapse (you can try the [first example](https://bootstrap-vue.org/docs/components/navbar)) when clicking any of the links.

**To Reproduce**
1. Copy [first example](https://bootstrap-vue.org/docs/components/navbar) to a bootstrap-vue-3 project
2. Click on any link in the navbar item list when expanded (i.e. narrow window)
3. Navbar item list remains expanded

**Expected behavior**
Navbar items should collapse after an item is clicked (especially in single page applications as often in Vue)

**Environment (please complete the following information):**
 - bootstrap-vue-3 0.3.5

**Comment by VividLemon** [comment]
Can you also post where you see it happening in bootstrap?

**Comment by memen45** [comment]
In the bootstrap docs for navbar [here](https://getbootstrap.com/docs/5.2/components/navbar/#supported-content), I also added the link above.
