### ISSUE TITLE
BFormGroup in undefined state adds class="is-invalid" and aria-invalid="true"

### ISSUE THREAD

**Issue by esl51** [bootstrap-vue/bootstrap-vue-next#807]
**Describe the bug**
I think, `BFormGroup` in `undefined` state must not contain the `class="is-invalid"` and `aria-invalid="true"`.
The issue https://github.com/cdmoro/bootstrap-vue-3/issues/554 references here, I think.

**To Reproduce**

```vue
<b-form-group :state="false" />
<b-form-group :state="true" />
<b-form-group :state="undefined" />
<b-form-group />
```

**Expected behavior**

![image](https://user-images.githubusercontent.com/3800914/201485244-6514b315-1b4e-4e4f-8d1f-a7ba4decc6e9.png)

**Screenshots**

![image](https://user-images.githubusercontent.com/3800914/201485106-18fb888d-f2a1-4d71-baa1-900c57750ea0.png)

**Environment (please complete the following information):**

 - OS: MacOS Monterey 12.6.1
 - Version: 0.4.7

**Comment by VividLemon** [comment]
BFormGroup is an outlier case where the correct way to get a "missing state" is to pass it null. It doesn't behave like the other components because it doesn't use script setup and isn't a `<template>`, rather it's a render function. Eventually it will be updated and more similar. Try passing "null", and let me know what the classes come out to be

**Comment by esl51** [comment]
In this case, the class is also added, but we also have an error.

![image](https://user-images.githubusercontent.com/3800914/201486536-66ebd505-350a-4788-b1b2-67a2cb8d7e54.png)

**Comment by VividLemon** [comment]
:exploding_head:

**Comment by esl51** [comment]
I think this is because `useBooleanish` only returns `boolean` (with `resolveBooleanish`) or `undefined` and state always converts to one of these types. Hence it is never `null`.

**Comment by VividLemon** [comment]
> I think this is because `useBooleanish` only returns `boolean` (with `resolveBooleanish`) or `undefined` and state always converts to one of these types. Hence it is never `null`.

No, it's because it's not in the list `state: {type: [Boolean, String] as PropType<Booleanish>, default: null},`

**Comment by esl51** [comment]
> > I think this is because `useBooleanish` only returns `boolean` (with `resolveBooleanish`) or `undefined` and state always converts to one of these types. Hence it is never `null`.
> 
> No, it's because it's not in the list `state: {type: [Boolean, String] as PropType<Booleanish>, default: null},`,
> 
> Which circles back to your issue that it's actually being passed in null, which resolveBooleanish doesn't know how to handle.

Yes. I meant adding a class, not a bug in the editor. I apologize.

**Comment by VividLemon** [comment]
> Yes. I meant adding a class, not a bug in the editor. I apologize.

Don't know what you mean. But actually I'd like to get the types overhauled a bit. There's some technical issues that make overhauling pretty much impossible atm. This could be fixed though,
