### ISSUE TITLE
CheckBox broken value/unchecked value

### ISSUE THREAD

**Issue by panhow** [bootstrap-vue/bootstrap-vue-next#813]
**Describe the bug**
when switch to true, switch won't slide to right

**To Reproduce**
```
<template>
  <b-form-checkbox
    v-model="check"
    :value="1"
    :unchecked-value="0"
    switch
  >
    switchTest
  </b-form-checkbox>
</template>
<script setup lang="ts">
const check = ref(0)
</script>
```

**Expected behavior**
switch will slide to right

**Environment (please complete the following information):**
 - OS: osx 12.2.1
 - Version 0.4.8

**Comment by VividLemon** [comment]
Try again 0.8
