### ISSUE TITLE
b-form-radio content not rendered

### ISSUE THREAD

**Issue by kris-sum** [bootstrap-vue/bootstrap-vue-next#823]
**Describe the bug**

`<b-form-radio>` elements inside `<b-form-radio-group>` do not appear to have their content slot rendered when project is built for production. The labels appear to be rendered when running in non-production builds, weirdly.

The current project documentation page shows this as the labels are not showing up in the second example:

![image](https://user-images.githubusercontent.com/2246940/205279051-87ce2a52-07ce-4824-8aac-71e7722c4124.png)

**To Reproduce**

     <b-form-radio-group id="radio-group-2" v-model="groupedSelected" name="radio-sub-component">
      <b-form-radio value="first">Toggle this custom radio</b-form-radio>
      <b-form-radio value="second">Or toggle this other custom radio</b-form-radio>
      <b-form-radio value="third" disabled>This one is Disabled</b-form-radio>
      <b-form-radio :value="{ fourth: 4 }">This is the 4th radio</b-form-radio>
    </b-form-radio-group>

**Expected behavior**
The radio items should have their label text rendered

**Environment (please complete the following information):**
bootstrap-vue-3 v0.4.11
bootstrap v5.1

**Comment by VividLemon** [comment]
Can you check and see if this is an issue on real applications? In all of my tests, I am managing to get all correct information. Even when running docs locally, it is fine. So, is this only an issue on the current docs?

**Comment by kris-sum** [comment]
> Can you check and see if this is an issue on real applications?

Yes, we noticed it when putting an app into production from dev, and it all works fine when using vue-cli-service to serve but it breaks when building for production.

**Comment by roelVerdonschot** [comment]
We have the same problem running our app in production mode.

"vue": "^3.2.0",
"bootstrap-vue-next": "^0.7.3",
"vite": "^4.0.0",

The checkbox grooup has the same problem.

**Comment by edwh** [comment]
I have what I think is the same problem, but it's working ok in dev for me, just not when deployed.

**Comment by VividLemon** [comment]
I will revisit this after 0.8, as the changes in that release may affect this issue.

**Comment by VividLemon** [comment]
Should be fixed in 0.8. The docs are broken... So I have to fix those, but feel free to reopen if the issue strangely persists.
