### ISSUE TITLE
Bootstrap component code is not getting converted into HTML.

### ISSUE THREAD

**Issue by yashwanth2714** [bootstrap-vue/bootstrap-vue-next#850]
### Vue version

3.2.45

### Link to minimal reproduction

https://github.com/DivakarSS/WebComponents

### Steps to reproduce

The issue is that bootstrap components are not getting converted into HTML.

Please click on the attached repo link and run demo.html file that is present in dist folder. It is generated using the following cmd:

vue-cli-service build --mode production --modern --target lib --inline-vue --name vue-select ./src/main.ts

### What is expected?

Bootstrap component is supposed to be converted into HTML.

### What is actually happening?

Bootstrap components remains the same in dist files. Compilation is not happening.

![image](https://user-images.githubusercontent.com/36370530/208447385-a7f62e12-76a8-4840-8fc1-c64b41994ab9.png)

### Any additional comments?

Please let us know if we are missing anything.

**Comment by VividLemon** [comment]
You'd probably be better off finding help elsewhere, as this is more of a Vue edge case problem. Perhaps you'd find better help in the vue official discord

**Comment by yashwanth2714** [comment]
@VividLemon We figured it out. We are using unplugin-vue-components library to mount bootstrap vue. However, bootstrap dropdown is not working. Nothing is happening when we click on the dropdown. It works fine in local env. Other components are working correctly.

Please run demo.html file that is in dist folder to reproduce the issue.
Bootstrap dropdown code is present in vselect-test1.vue

**Comment by VividLemon** [comment]
The dropdown not working is likely because it needs to be fixed. There is a small portion of components that need to be rewritten to fix their issues, and dropdown is one of them.
