### ISSUE TITLE
b-form-checkbox sm and lg styling wrong when using button style

### ISSUE THREAD

**Issue by xmatthias** [bootstrap-vue/bootstrap-vue-next#857]
**Describe the bug**

When using b-form-checkbox in button mode, i'd assume they get the same sizing as a regular button.
Rendering these next to each other shows that this is only the case for "non-sized" buttons - but on sm and lg styles, the checkbox is offset.

The problematic part seems to be the padding set in  `form-control-<size>`.

![image](https://user-images.githubusercontent.com/5024695/209431282-9b7f6e2c-8fe3-430c-84d4-98903f89eec9.png)

I could neither find the definition of this in the code - nor am i certain what other (negative?) side-effects changing this might have to other components.

**To Reproduce**
Reproduction stackblitz:
https://stackblitz.com/edit/vue3-script-setup-with-vite-lxjcyo?file=package.json,src%2Fmain.js,src%2FApp.vue,src%2Fcomponents%2FHelloWorld.vue

**Expected behavior**

Both buttons have the same height, and no additional padding which can't be overridden without using negative margins on the checkbox.

**Screenshots**
Left is always the button, right the checkbox.
Only the "medium" buttons are shown as they should be.

![image](https://user-images.githubusercontent.com/5024695/209431104-ed567a59-684e-41a2-b187-c23d32fcf590.png)

**Environment (please complete the following information):**

 - Version 0.4.15 / (also on main as of today)

**Comment by xmatthias** [comment]
Uppon looking at this further - this can be fixed by changing the below line to

https://github.com/cdmoro/bootstrap-vue-3/blob/ad9c14501738446516ccf58ce2e00791966ad822/packages/bootstrap-vue-3/src/composables/useFormCheck.ts#L20

```
    [`form-control-${items.size}`]:
      items.size !== undefined && items.size !== 'md' && items.button === false,
```

I'm however unclear if this is the desired / correct fix (and what side-effects on other components this might have).

If you think this is correct let me know - and i can provide this as a PR.

**Comment by VividLemon** [comment]
It's a band-aid to the core issue that when initially writing the component, they wrote it wrong. They confused labelClasses with btnClasses. Regardless Bootstrap v4 implemented this functionality in a hacky way, and both BFromCheckbox and BFormGroup button groups can be overhauled to simpler syntax
