### ISSUE TITLE
Docs are down 

### ISSUE THREAD

**Issue by YosefOberlander** [bootstrap-vue/bootstrap-vue-next#866]
When visiting https://cdmoro.github.io/bootstrap-vue-3/ I get a 404.

OS: macOS Ventura
Browser: Chrome, Safari, Firefox

**Comment by VividLemon** [comment]
Yeah, its going to be like that for a bit while transitipning

**Comment by YosefOberlander** [comment]
Thanks for the quick update :)

**Comment by tomscytale** [comment]
I can understand why this might happen, but it's a very poor experience for people who might want to use the software despite its beta status. Surely you could leave the documentation site up during the transition?

In case anyone else needs it - the documentation was archived here:
https://web.archive.org/web/20221130081310/https://cdmoro.github.io/bootstrap-vue-3/getting-started/

**Comment by VividLemon** [comment]
The docs are impossible to host in the current state. The site available in the bootstrap-vue organization, I do not believe the domain is owned by bootstrap-vue. This is most likely because the docs are hosted on Vercel. 

Regardless, anyone can open the docs by cloning the repo and running dev

**Comment by tomscytale** [comment]
I tried cloning the repo but `npm install` fails due to use of non-standard url in `package.json`

```
$ npm install
npm ERR! code EUNSUPPORTEDPROTOCOL
npm ERR! Unsupported URL Type "workspace:": workspace:*
```

`package.json`:
```js
   "devDependencies": {
     "eslint-config-custom": "workspace:*",
     ...
```

Also running dev is not how developers usually expect to build the docs.

The lack of easily accessible html documentation is going to make life difficult for anyone using the project until the transition is complete. 

I would do this myself but for the issue with running `npm install`

How about adding a few lines to the top-level README explaining how to install the project and build the html docs?

**Comment by tomscytale** [comment]
#872

**Comment by VividLemon** [comment]
https://bootstrap-vue.github.io/bootstrap-vue-next/

**Comment by YosefOberlander** [comment]
When visiting https://cdmoro.github.io/bootstrap-vue-3/ the page is blank.

OS: macOS Ventura
Browser: Chrome, Safari, Firefox

**Comment by VividLemon** [comment]
> When visiting https://cdmoro.github.io/bootstrap-vue-3/ the page is blank.
> 
> OS: macOS Ventura Browser: Chrome, Safari, Firefox

https://github.com/bootstrap-vue/bootstrap-vue-next/issues/866#issuecomment-1382127855

**Comment by YosefOberlander** [comment]
@VividLemon my bad for using the old link but https://bootstrap-vue.github.io/bootstrap-vue-next/ also seems to be a blank page.
