### ISSUE TITLE
docs website is 404

### ISSUE THREAD

**Issue by heshimang** [bootstrap-vue/bootstrap-vue-next#870]
**Describe the bug.** The [website](https://cdmoro.github.io/bootstrap-vue-3/) is 404

**To Reproduce.** Steps to reproduce the behavior:

1. Go to 'https://cdmoro.github.io/bootstrap-vue-3/'

**Screenshots.** 
<img width="1286" alt="image" src="https://user-images.githubusercontent.com/19547994/211442692-01932891-44ed-49db-b8f1-b61257f51ef6.png">

**Environment (please complete the following information):**

- OS: [MacOS m1 chrome 108.0.5359.124]

**Additional context.**  I really need this. Please repair as soon as possible

**Comment by VividLemon** [comment]
https://github.com/bootstrap-vue/bootstrap-vue-next/issues/866
Duplicate. I have reopened that and will pin it. I'm not sure why the author closed it. But I will likely need to try to get in contact with pi0 for this

**Comment by VividLemon** [comment]
https://bootstrap-vue.github.io/bootstrap-vue-next/
