### ISSUE TITLE
collapse not working

### ISSUE THREAD

**Issue by aljaznuncic** [bootstrap-vue/bootstrap-vue-next#871]
Since I use bootstrap-vue-3 version 0.5.1, bootstrap collapse is not working (bootstrap version 5.2.3). It opens collapsed div, but when you want to close it, does not close. Classes applied to div are collapse show, than collapsing and collapse show again (not just collapse). If I remove bootstrap-vue-3 everything works right.

**Comment by RuBaWa** [comment]
It's them same problem as mentioned here:

[Issue 764](https://github.com/bootstrap-vue/bootstrap-vue-next/issues/764)

**Comment by NNeto** [comment]
In the console is shown `Failed to resolve directive: b-toggle`. The examples in the docs also stopped working while the example using `v-model` still works.

**Comment by VividLemon** [comment]
Aware.

**Comment by mackoLee-EIP** [comment]
using v-model not include ```.collapsing``` class. so opening collapse isn't soft.

.collapsing {
    height: 0;
    overflow: hidden;
    transition: height .35s ease;
}

**Comment by xvaara** [comment]
fixed in v0.8
@VividLemon close
