### ISSUE TITLE
Package name in docs installs empty package

### ISSUE THREAD

**Issue by artm4r** [bootstrap-vue/bootstrap-vue-next#875]
https://bootstrap-vue.github.io/bootstrap-vue-next/getting-started/#installation-vue-js
Docs are saying that we need to install package called bootstrap-vue-next

But this package on npmjs in empty
https://www.npmjs.com/package/bootstrap-vue-next

**Comment by VividLemon** [comment]
This is something I am planning on getting to later today. Pi0 gave me access to those repositories a few hours ago

**Comment by VividLemon** [comment]
https://www.npmjs.com/package/bootstrap-vue-next
