### ISSUE TITLE
b-form-radio-group not behaving as expected when value which in options equal to 0

### ISSUE THREAD

**Issue by xupapa** [bootstrap-vue/bootstrap-vue-next#931]
**Describe the bug.** A clear and concise description of what the bug is.

**To Reproduce.** Steps to reproduce the behavior:

1. Click on radio
2. radio item can't be checked well

**Expected behavior.** A clear and concise description of what you expected to happen.

**Screenshots.** If applicable, add screenshots to help explain your problem.

**Environment (please complete the following information):**

- OS: Mac 13.1
- Package Version: v0.7.3
- Npm/Yarn/Pnpm Version: yarn@1.22.15

**Additional context.** Add any other context about the problem here.

I think there is something wrong with the following logic maybe

https://github.com/bootstrap-vue/bootstrap-vue-next/blob/main/packages/bootstrap-vue-next/src/components/BFormRadio/BFormRadio.vue
![WX20230213-173810@2x](https://user-images.githubusercontent.com/23093799/218423142-7570463d-56f7-41f7-81f9-7f6899acbf0c.png)

**Comment by xupapa** [comment]
you can try this  https://codesandbox.io/s/boring-http-f95zdz?file=/src/App.vue

**Comment by VividLemon** [comment]
Was fixed in 0.8.2
