### ISSUE TITLE
[Vue warn]: injection "Symbol()" not found. 

### ISSUE THREAD

**Issue by roelVerdonschot** [bootstrap-vue/bootstrap-vue-next#932]
**Describe the bug.** A clear and concise description of what the bug is.
On some elements I get the Vue warning: 'injection "Symbol()" not found.'

**Environment (please complete the following information):**

- OS: Apple Ventura 13.1
- Package Version: 0.7.3
- Npm Version: 9.4.1
- Vue: 3.2.47
- Vite: 4.1.1

**Additional context.** Add any other context about the problem here.
[Vue warn]: injection "Symbol()" not found. 
  at <BListGroupItem data-draggable=true >

**Comment by sagacity-felix** [comment]
This warning also occurs for us when we use the accordion component.
