### ISSUE TITLE
b-form-group :label-cols="true" not working.

### ISSUE THREAD

**Issue by xvaara** [bootstrap-vue/bootstrap-vue-next#934]
```html
<b-form-group label="label"  :label-cols="true">
```

causes warning:
```
[Vue warn]: Invalid prop: type check failed for prop "cols". Expected String | Number, got Boolean with value true. 
  at <BCol onClick=fn<onLegendClick> cols=true tag="legend"  ... > 
  at <BFormRow> 
  at <BFormGroup label="label" label-cols=true > 
```

I believe thats because we don't check for boolean on the default xs breakpoint at:
https://github.com/bootstrap-vue/bootstrap-vue-next/blob/main/packages/bootstrap-vue-next/src/components/BFormGroup/BFormGroup.vue#L130-L134

**Comment by VividLemon** [comment]
What is the expected output if having the value be a boolean? Can you show relevant bootstrap or bootstrap vue code?

**Comment by xvaara** [comment]
it creates a row with:
```html
<div class="row d-flex flex-wrap mb-3">
```
Now I have to use either: :label-cols-sm="true" which generates:
```html
  <label class="col-sm col-form-label col-form-label" for="x">x</label>
```
or :label-cols="1" which generates:
```html
<label class="col-1 col-form-label col-form-label">
```

I'd like to have the col responsive for all, so :label-cols="true" should generate:
```html
<label class="col col-form-label col-form-label">
```
That's what the bootstrap-vue-next documentation btw says it should do.
