### ISSUE TITLE
split-to option is not working in b-dropdown

### ISSUE THREAD

**Issue by roelVerdonschot** [bootstrap-vue/bootstrap-vue-next#939]
**Describe the bug.**
The b-dropdown component split-to option is not working. 
https://bootstrap-vue.github.io/bootstrap-vue-next/components/Dropdown.html#split-button-link-support 

**To Reproduce.** Steps to reproduce the behavior:

1. add b-dropdown component
2. enable split and add split-to prop
3. Click the split button
4. Not redirected

**Expected behavior.** 
Redirected to correct page

**Environment (please complete the following information):**
"bootstrap-vue-next": "^0.7.3",

**Comment by VividLemon** [comment]
Will review after 0.8.0 as it may be fixed already

**Comment by roelVerdonschot** [comment]
When is 0.8.0 being released?

**Comment by xvaara** [comment]
There isn't a split-to option in dropdown code (mistake, lot's of moving parts.), for now you can use the @click="$router.push('/page')" to enable navigation.

**Comment by xvaara** [comment]
fixed in 0.8
@roelVerdonschot 0.8 is released

@VividLemon close
