### ISSUE TITLE
BDropdown with auto-close=false closes the dropdown by pressing esc key

### ISSUE THREAD

**Issue by jclijmans** [bootstrap-vue/bootstrap-vue-next#94]
According to the Bootstrap 5 documentation :

> autoclose  boolean | string  true
> false - the dropdown will be closed by clicking the toggle button and manually calling hide or toggle method. (Also will not be closed by pressing esc key)

I've tested the current implementation and the dropdown closes when you press esc.
At least when the dropdown has focus.

I've tested the same behavior at the Bootstrap 5 doc site : [see here](https://getbootstrap.com/docs/5.0/components/dropdowns/#auto-close-behavior) and the dropdown is not closed using the esc key.

**Comment by VividLemon** [comment]
Though the docs say that, I have different experience with more up to date versions (https://getbootstrap.com/docs/5.3/components/dropdowns/#auto-close-behavior & https://getbootstrap.com/docs/5.2/components/dropdowns/#auto-close-behavior). I'm going to open up a ticket about this to Bootstrap, but as it stands, in our v0.8.0, auto-close behavior should behave exactly as the two examples I provided.

**Comment by VividLemon** [comment]
Review https://github.com/twbs/bootstrap/issues/38035 for latest information
