### ISSUE TITLE
<b-embed> : failed to resolve component (bug or what?)

### ISSUE THREAD

**Issue by amdp** [bootstrap-vue/bootstrap-vue-next#943]
I am using a b-embed tag to embed a video. I get:

```
[Vue warn]: Failed to resolve component: b-embed                                                                                                11:02:58
If this is a native custom element, make sure to exclude it from component resolution via compilerOptions.isCustomElement.
```

All other many b-tags work on my project.

**To Reproduce.** 

```
<b-embed
  type="video"
  autoplay
  controls
>
  <source src="video.mp4" type="video/mp4" />
</b-embed>
```

**Expected behavior.** A clear and concise description of what you expected to happen.
The video to appear and play

**Screenshots.** If applicable, add screenshots to help explain your problem.
not applicable

**Environment (please complete the following information):**

macosx, chrome, both latest, below my packages

**Additional context.** Add any other context about the problem here.

  "scripts": {
    "build": "nuxt build",
    "dev": "nuxt dev",
    "generate": "nuxt generate",
    "preview": "nuxt preview",
    "postinstall": "nuxt prepare"
  },
  "devDependencies": {
    "@nuxt/image-edge": "^1.0.0-27840416.dc1ed65",
    "@nuxtjs/i18n": "^8.0.0-beta.3",
    "@popperjs/core": "^2.11.6",
    "@sidebase/nuxt-auth": "^0.4.0-alpha.3",
    "@types/bcryptjs": "^2.4.2",
    "@types/jsonwebtoken": "^9.0.1",
    "@types/nodemailer": "^6.4.7",
    "bcryptjs": "^2.4.3",
    "body-parser": "^1.20.1",
    "bootstrap": "^5.2.3",
    "bootstrap-vue-next": "^0.6.7",
    "express": "^4.18.2",
    "express-fileupload": "^1.4.0",
    "jimp": "^0.16.2",
    "jsonwebtoken": "^9.0.0",
    "mysql": "^2.18.1",
    "mysql2": "^2.3.3",
    "nodemailer": "^6.8.0",
    "nuxt": "^3.2.2",
    "sass": "^1.56.1"
  },
  "dependencies": {
    "@pinia/nuxt": "^0.4.7",
    "pinia": "^2.0.32",
    "vue-recaptcha-v3": "^2.0.1"
  },
  "overrides": {
    "vue": "latest"
  }
}

**Comment by VividLemon** [comment]
Does not exist

**Comment by amdp** [comment]
Alright so best practice now is to use the native video tag directly. It's working for me with a styling similar to parent tag. Thanks
