### ISSUE TITLE
b-offcanvas does not accept a class, name, style, id and spoiles document.body

### ISSUE THREAD

**Issue by alsun** [bootstrap-vue/bootstrap-vue-next#949]
**Describe the bug:** 

1. b-offcanvas does not accept a class, name, style, id, or any other attribute. Is there another way to change the width of b-offcanvas?
2. If b-offcanvas is created with v-model="true", it has attributes before the first close. And also style="overflow: hidden; padding-right: 0px;" on document.body which are never be removed after.

**To Reproduce:** 
1. Make vue
```
<template>
  <b-offcanvas
    v-model="show"
    class="test"
    id="test"
    style="background-color: lime"
  >TEMP</b-offcanvas>
</template>
<script>
export default {
  data() {
    return {
      show: true,
    };
  },
}
</script>
```
2. Look at Inspector
3. See error

**Expected behavior:** 

- DIV.offcanvas has attributes from template.
- document.body hasn't style.

**Environment:**

- OS: MacOS 10.15.7
- npm -v 9.3.1

**Comment by VividLemon** [comment]
It may be best to use the bootstrap variables in this case. I don't think traditional classes and styles work well with offcanvas

**Comment by alsun** [comment]
> use the bootstrap variables

```
v-model="show"
...
data() {
    return {
      show: true,
    };
  },
```
Is it not ok?

**Comment by VividLemon** [comment]
> > use the bootstrap variables
> 
> ```
> v-model="show"
> ...
> data() {
>     return {
>       show: true,
>     };
>   },
> ```
> 
> Is it not ok?

I'm not sure how this pertains to the issue
