### ISSUE TITLE
b-modal[hide.prevent] won't let me hide it with a callback on @ok, @cancel, etc.

### ISSUE THREAD

**Issue by bradlis7** [bootstrap-vue/bootstrap-vue-next#951]
**Describe the bug.** A clear and concise description of what the bug is.

Adding `hide.prevent` does not allow custom events on b-modal to hide the modal.

**To Reproduce.** Steps to reproduce the behavior:

```
<script>
const showModal = ref(false)
</script>
<template>
  <div>
    <button @click.prevent="showModal = true">Show Modal</button>
    <b-modal v-model='showModal' @hide.prevent @ok="showModal = false">
  </div>
</template>
```

**Expected behavior.** Hiding the modal from `@ok`, and other callbacks should work.

**Screenshots.** N/A

**Environment (please complete the following information):**

- OS: Windows 10
- Package Version: 0.7.3
- Npm/Yarn/Pnpm Version: npm

**Additional context.** N/A

**Comment by amadare42** [comment]
@VividLemon not sure if that is the same issue, but I encountered the following:
If I do `@click="modalShown = true"` modal is shown as expected, but nothing is happening when I do `@click="showModal"` with showModal defined as 
```js
function showModal() { 
    modalShown = true
}
```

Same behavior is for hiding modal. `nextTick(() => showModal = true)` didn't help either.

**Comment by VividLemon** [comment]
Assuming your code is exact replica, you'd likely are assigning a ref and missing .value, or the "this." Context if using options api

**Comment by amadare42** [comment]
yes, you are correct, that was really the case and issue was on my side. Sorry, and thank you!
