### ISSUE TITLE
Nested BCollapse closes parent on close and does trigger parent @shown on open

### ISSUE THREAD

**Issue by bettysteger** [bootstrap-vue/bootstrap-vue-next#961]
**Describe the bug.** 

I found 2 issues when using nested BCollapse:

1. When i add an @shown emit to the parent `<b-collapse>` - it also gets triggered when opening the inner BCollapse.
2. When i have a reference list and use v-model, somehow the parent BCollapse gets closed when I close the inner BCollapse.

**To Reproduce.** 

1. Go to [this codesandbox](https://codesandbox.io/p/sandbox/vue-project-forked-w6swi3?file=%2Fsrc%2FApp.vue&selection=%5B%7B%22endColumn%22%3A13%2C%22endLineNumber%22%3A19%2C%22startColumn%22%3A13%2C%22startLineNumber%22%3A19%7D%5D), and click "Parent". The counter increments. Click on "Child1" the counter should **not** increment.
2. Go to [this codesandbox](https://codesandbox.io/p/sandbox/vue-project-forked-yfg03j?file=%2Fsrc%2FApp.vue&selection=%5B%7B%22endColumn%22%3A8%2C%22endLineNumber%22%3A22%2C%22startColumn%22%3A8%2C%22startLineNumber%22%3A22%7D%5D), and click "Child1". Close "Child1", the parent closes as well. 

**Expected behavior.** 

1. `@shown` emit of parent should not be triggered, when child is shown.
2. Parent should not close when inner BCollapse is closed.

**Environment:**

- OS: Mac OSX
- Package Version: 0.7.3

**Comment by VividLemon** [comment]
https://sfc.vuejs.org/#eNqFUj1PwzAU/CsPL0klSNSOUVoVISR2BhYvbeKkLrafZTvtEOW/44+UtiDE5pfz3fPdZSTPWhengZGK1LYxXDuwzA16QxUAlxqNgxeUGjqDErKiDEMgZFTN8AiGdTDNNxJEVYPKOpC2h3XA8+yNCYHwgUa0D9nieqXFdzd03dLfyxew3sAYVgcMBSsE9nlmD3hWsAys6Rdx9S9xNRPrMjn03vzgmNRi55if6pafouE6Wt1G2pqSy9Moiegf8MrDHWIdo0kyt8ekXZff+8gjSck9yZ0ujhaVDz++nc6ApaRKbsI3n2iYKTk4p21VlrZrQgNHW6DpS38qzKAcl6xgVj7tDZ4tM16YkiDhjU9+5aW3UPSt9f3gHCrYNoI3n4V1qK/OZt+1FeignP0kwr2lGOjt7wNip3ovFKx4NBXGJHe+rJZ1XLFXP9h6zFkFqaZsUcEJeTttfJsxjfue72sOWnO/P9sl0xfHbvW3

For reference

**Comment by xvaara** [comment]
fixed in v0.8

@VividLemon close
