### ISSUE TITLE
BFormSelect doesn't allow null for v-model

### ISSUE THREAD

**Issue by dpash** [bootstrap-vue/bootstrap-vue-next#962]
With Bootstrap-Vue, the following will work:

    <b-form-select v-model="country_code" :options="countryStore.countries" value-field="country_code" text-field="name">
        <template #first>
            <option :value="null">All markets</option>
        </template> 
    </b-form-select>
    ...
    data: () => ({
        country_code: null as string | null,
    }),

However in Bootstrap-Vue-next vue-tsc gives:

    example.vue:17:40 - error TS2322: Type 'string | null' is not assignable to type 'string | number | unknown[] | Record<string, any> | undefined'.

    17                         <b-form-select v-model="country_code" :options="countryStore.countries" value-field="country_code" text-field="name">

Vite will happily compile and when running, the component works perfectly fine, so I don't think there's any reason to disallow null.

The prop is currently typed as `modelValue?: string | Array<unknown> | Record<string, unknown> | number`. I propose it be changed to `string | Array<unknown> | Record<string, unknown> | number | null`.

While I can set everything to undefined, I believe null is the correct type for my situation.

**Comment by VividLemon** [comment]
I agree. Globally there is an issue of props not being allowed to be assigned null. This needs to be done prior to 1.0, but will likely be the third on my list of things to do (Nuxt support -> BTable refactor -> Null values in props -> Bootstrap-vue consistency -> 1.0?)

**Comment by dpash** [comment]
Perfect. This was pretty much the only place I noticed it breaking for us during the migration. I'll use undefined for now and change back to null when 1.0 is released.

Thanks.

**Comment by VividLemon** [comment]
I had forgotten why I had originally made this change in the first place... The issue stems from a Vue compiler issue that fails when certain limitations are met. This is most likely an issue that cannot be fixed until the next minor release of Vue 3 -- 3.3. It is near impossible to declare complex types of this nature. I'll try my best to see if theres a solution, but this may not come out for awhile.

**Comment by boindil** [comment]
> Perfect. This was pretty much the only place I noticed it breaking for us during the migration. I'll use undefined for now and change back to null when 1.0 is released.
> 
> Thanks.

Did that work for you? When I select an option with the value being `undefined`, the v-model value becomes the "text" attribute of that option.
