### ISSUE TITLE
`<BModal>` is not closed when pressing ESC-Key as in vanilla Bootstrap

### ISSUE THREAD

**Issue by Atokulus** [bootstrap-vue/bootstrap-vue-next#964]
Dear community
I hope you are well 😄

## The Bug

When having a modal opened and pressing the ESC-key, the modal is not closed as it would in vanilla Bootstrap.

See the updated examples for:

* Vue Bootstrap Next: https://codesandbox.io/s/bootstrap-vue-next-modal-close-bug-on-esc-key-h4ygm3?file=/src/App.vue
* Vanilla Bootstrap: https://codepen.io/atok/pen/YzOYKbL

## Remarks

I filed this bug once, yet after the migration to the new [bootstrap-vue-next](https://github.com/bootstrap-vue/bootstrap-vue-next) repository, the issue seems to be still present.

See

* https://github.com/bootstrap-vue/bootstrap-vue-next/issues/674
* https://github.com/bootstrap-vue/bootstrap-vue-next/pull/677

Cheers
Markus

**Comment by VividLemon** [comment]
The element needs to be focused.
