### ISSUE TITLE
Add `.modal-open` class to body if any modal is open

### ISSUE THREAD

**Issue by thetarnav** [bootstrap-vue/bootstrap-vue-next#976]
Hi, I am wondering if there are plans to support adding a `.modal-open` class to `document.body` whan any bootstrap modal is currently open?

We relied on this feature in vue 2 to apply additional styles to the body - changing the background color or bluring the content underneeth.

This is a hard thing to work around when you don't control the implementation of b-modal, so it would be nice to have this considered, or have an official alternative.

in vue 2:

![image](https://user-images.githubusercontent.com/24491503/227170052-e76ef6ed-952f-44d6-a0a2-b2e1440e03ec.png)

in vue 3:

![image](https://user-images.githubusercontent.com/24491503/227170603-d093a555-3269-45c0-b48a-810243ff1e91.png)

**Comment by VividLemon** [comment]
Relates https://github.com/bootstrap-vue/bootstrap-vue-next/issues/1030
