### ISSUE TITLE
BFormCheckboxGroup with slots not working

### ISSUE THREAD

**Issue by forchel** [bootstrap-vue/bootstrap-vue-next#983]
I tried to use the BFormCheckboxGroup built with options from the default slot. But if I click on one of the option, the v-model value is not updated. This can be easily reproduced in the examples provided.

1. Go to example 'TFormCheckboxGroup' and the checkbox group built with slots
2. Click on one of the not selected checkboxes 'Orange' (or each other)
3. There are no changes on the selected model value
4. Deselect a value works by the way

Should behave like clicking on the checkbox built with options.

- Package Version: 0.7.3

Screenshots:

![Firefox_Screenshot_2023-03-29T14-56-01 244Z](https://user-images.githubusercontent.com/1374686/228580144-1145b0e2-272d-4bcd-a079-4be9da5be5f5.png)
![Firefox_Screenshot_2023-03-29T14-56-51 772Z](https://user-images.githubusercontent.com/1374686/228580149-10ec34d0-9fe4-49f8-9318-9f5237b33e17.png)

**Comment by VividLemon** [comment]
Are you copying the code from the TFormCheckboxGroup, and using it in a outside package? Or are you opening the playground internally with our dev

**Comment by forchel** [comment]
> Are you copying the code from the TFormCheckboxGroup, and using it in a outside package? Or are you opening the playground internally with our dev

I was copying your code from the TFormCheckbox into our project to test whether it works or not, because I noticed before that the change event was not emitted (although it should).

**Comment by forchel** [comment]
> Which event? Are you referring to the one submitted by the group, or the child?

I assume, it was the child event (not sure)

**Comment by VividLemon** [comment]
I'd suggest testing this out on the actual playground
ie
```bash
git clone ${project}
pnpm i (have pnpm installed)
pnpm dev
```

Then open the playground one (a bunch are made)
Then check to see if it's working as intended. The checkbox, as well as radio have been overhauled to address multiple issues around these two compoonent trees.

**Comment by forchel** [comment]
Okay, I followed your instruction and opened the playground. It works on your playground as intended. So please close this issue.
